version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file: ./docker/app/.env
    environment:
      - TERM=xterm-256color
    volumes:
      - app-node-modules:/srv/mobx-starter/node_modules
      - app-npm-cache:/root/.npm

  storybook:
    build:
      context: .
      dockerfile: ./docker/storybook/Dockerfile
    environment:
      - TERM=xterm-256color
    volumes:
      - storybook-node-modules:/srv/mobx-storybook-starter/node_modules
      - storybook-npm-cache:/root/.npm

volumes:
  app-node-modules: {}
  app-npm-cache: {}
  storybook-node-modules: {}
  storybook-npm-cache: {}
